/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Apple.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Apple(props) {
  const { nodes, materials } = useGLTF('/Apple.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.apple__0.geometry} material={materials['Scene_-_Root']} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/Apple.glb')
